### ISSUE TITLE
Question about GPU Limitations

### ISSUE THREAD

**Issue by nemesisXX** [Jyonn/Legommenders#13]
Hi there,

Sorry to bother you again. We have resolved all issues with configuration, naming errors, etc., but we're currently facing challenges with training preparation and testing due to GPU limitations. We're considering whether simplifying the model or applying data distillation on the original Goodreads dataset (planning to use only the Goodreads dataset since it's smaller) could help overcome this obstacle.  But none of them works. We would greatly appreciate your guidance if you have encountered similar issues or have any references or papers that might address this problem.

Thank you for your help!
And here's the command we use and what we lack:
**For the training preparation:** 

**python  worker.py --embed config/embed/llama-token.yaml --model config/model/llm/llama-naml.yaml --exp config/exp/llama-split.yaml --data config/data/goodreads-llama.yaml --llm_ver 7b --layer 0 --lora 0 --embed_hidden_size 4096**

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 538.00 MiB. GPU 0 has a total capacity of 44.48 GiB of which 423.31 MiB is free. Including non-PyTorch 
memory, this process has 44.06 GiB memory in use. Of the allocated memory 43.82 GiB is allocated by PyTorch, and 51.65 MiB is reserved by PyTorch but unallocated.

**For the training and testing:**

**python worker.py \
  --data config/data/goodreads-llama.yaml \
  --embed config/embed/llama-token.yaml \
  --model config/model/llm/llama-naml.yaml \
  --exp config/exp/tt-llm.yaml \
  --embed_hidden_size 4096 \
  --llm_ver 7b \
  --layer 0 \
  --version small \
  --lr 0.0001 \
  --item_lr 0.00001 \
  --batch_size 32 \
  --acc_batch 2 \
  --epoch_batch -4**

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacity of 44.48 GiB of which 41.31 MiB is free. Including non-PyTorch me
mory, this process has 44.44 GiB memory in use. Of the allocated memory 44.09 GiB is allocated by PyTorch, and 156.03 MiB is reserved by PyTorch but unallocated.

**Comment by Jyonn** [comment]
Please refer to #6 .

**Comment by nemesisXX** [comment]
Hi Jyonn,
I've tried all the solutions in the previous work, but I tried every page_size from 32, 64, 128, 256, and 512, but none of them solved the OOM problem. Since I'm using ---model llama-naml.yaml and dataset Goodreads, so maybe there's something different? I copied the entire info about my work here for reference. And for the GPU, we only have:

> GPU Model: Tesla V100-PCIE-32GB
> CUDA Version: 12.2
> Driver Version: 535.154.05
> Total Memory: 32 GB (32768 MiB)

```bash
(nlp_env) Singularity> python worker.py --embed config/embed/llama-token.yaml --model config/model/llm/llama-naml.yaml --exp config/exp/llama-split.yaml --data config/data/goodreads-llama.yaml --llm_ver 7b --la
yer 0 --lora 0 --embed_hidden_size 4096
[00:00:00] |Worker| START TIME: 2024-11-11 23:43:26.837612
[00:00:00] |Worker| python  worker.py --embed config/embed/llama-token.yaml --model config/model/llm/llama-naml.yaml --exp config/exp/llama-split.yaml --data config/data/goodreads-llama.yaml --llm_ver 7b --layer 0 --lora 0 --embed_hidden_size 4096
[00:00:00] |Worker| {
    "embed": {
        "name": "llama-token",
        "embeddings": [
            {
                "vocab_name": "llama",
                "vocab_type": "numpy",
                "path": "data/llama-token.npy",
                "frozen": true
            }
        ]
    },
    "model": {
        "name": "LLAMA-NAML.D64.L0.Lora0",
        "meta": {
            "item": "Llama",
            "user": "Ada",
            "predictor": "Dot"
        },
        "config": {
            "use_neg_sampling": true,
            "use_item_content": true,
            "max_item_content_batch_size": 512,
            "same_dim_transform": false,
            "embed_hidden_size": 4096,
            "hidden_size": 64,
            "neg_count": 4,
            "item_config": {
                "llm_dir": "meta-llama/Llama-2-7b-hf",
                "layer_split": 0,
                "lora": 0,
                "weights_dir": "data/Goodreads-Llama/llama-7b-split"
            },
            "user_config": {
                "num_attention_heads": 12,
                "inputer_config": {
                    "use_cls_token": false,
                    "use_sep_token": false
                }
            }
        }
    },
    "exp": {
        "name": "test_llm_layer_split",
        "dir": "saving/Goodreads-Llama/LLAMA-NAML.D64.L0.Lora0/llama-token-test_llm_layer_split",
        "log": "saving/Goodreads-Llama/LLAMA-NAML.D64.L0.Lora0/llama-token-test_llm_layer_split/exp.log",
        "mode": "test_llm_layer_split",
        "store": {
            "layers": [
                31,
                30,
                29,
                27
            ],
            "dir": "data/Goodreads-Llama/llama-7b-split"
        },
        "load": {
            "save_dir": null,
            "model_only": true,
            "strict": true,
            "wait": false
        },
        "policy": {
            "device": "gpu",
            "batch_size": 64
        }
    },
    "data": {
        "name": "Goodreads-Llama",
        "base_dir": "data/Goodreads",
        "item": {
            "filter_cache": true,
            "depot": "data/Goodreads/book-llama",
            "order": [
                "title"
            ],
            "append": [
                "bid"
            ]
        },
        "user": {
            "filter_cache": true,
            "depots": {
                "train": {
                    "path": "data/Goodreads/train"
                },
                "dev": {
                    "path": "data/Goodreads/dev"
                },
                "test": {
                    "path": "data/Goodreads/test"
                }
            },
            "filters": {
                "history": [
                    "x"
                ]
            },
            "union": [
                "data/Goodreads/user"
            ],
            "candidate_col": "bid",
            "clicks_col": "history",
            "label_col": "click",
            "neg_col": "neg",
            "group_col": "uid",
            "user_col": "uid",
            "index_col": "index"
        }
    },
    "llm_ver": "7b",
    "layer": 0,
    "lora": 0,
    "embed_hidden_size": 4096,
    "warmup": 0,
    "fast_eval": true,
    "simple_dev": false,
    "batch_size": 64,
    "acc_batch": 1,
    "lora_r": 32,
    "lr": 0.0001,
    "item_lr": 1e-05,
    "mind_large_submission": false,
    "hidden_size": 64,
    "epoch_batch": 0,
    "max_item_batch_size": 0,
    "page_size": 512,
    "patience": 2,
    "epoch_start": 0,
    "frozen": true,
    "load_path": null,
    "rand": {},
    "time": {},
    "seed": 2023
}
[00:00:00] |GPU| choose 0 GPU with 32497 / 32768 MB
[00:00:00] |Controller| dataset type:  book
[00:00:00] |Controller| build column map ...
loaded 71021 samples from data/Goodreads/test
[00:00:00] |CachingDep| load 1 filter caches on 
        UniDep (2.0): data/Goodreads/test
        
        Sample Size: 71021
        Id Column: index
        Columns:
                index, vocab index (size 71021)
                uid, vocab uid (size 23089)
                bid, vocab bid (size 16833)
                click, vocab click (size 2)

loaded 68022 samples from data/Goodreads/dev
modify sample_size to 23089
loaded 23089 samples from data/Goodreads/user
[00:00:00] |Depots| Filter history with x in test phase, sample num: 71021 -> 71021
loaded 16833 samples from data/Goodreads/book-llama
[00:00:00] |Controller| Selected Item Encoder: LlamaOperator
[00:00:00] |Controller| Selected User Encoder: AdaOperator
[00:00:00] |Controller| Selected Predictor: DotPredictor
[00:00:00] |Controller| Use Negative Sampling: True
[00:00:00] |Controller| Use Item Content: True
[00:00:00] |EmbeddingHub| load pretrained embedding llama of torch.Size([32000, 4096])
[00:00:00] |EmbeddingHub| skip col history
[00:00:00] |EmbeddingHub| create vocab __cat_inputer_special_ids (3, 4096)
[00:00:00] |EmbeddingHub| create vocab __flatten_seq_special_ids (4, 4096)
[00:00:01] |EmbeddingHub| build mapping title -> llama
[00:00:01] |EmbeddingHub| load frozen vocab: llama torch.Size([32000, 4096])
[00:00:01] |EmbeddingHub| keep transform size 4096
/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.41s/it]
Some weights of the model checkpoint at meta-llama/Llama-2-7b-hf were not used when initializing LlamaModel: ['lm_head.weight']
- This IS expected if you are initializing LlamaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16833/16833 [00:01<00:00, 16783.54it/s]
[00:00:55] |Worker| {'index': 0, 'uid': 0, 'bid': 14740, 'click': 1, 'history': [6007, 170, 11990, 4649, 6975], 'neg': [7529, 2667, 2068, 10208, 1637, 16555, 15859, 11968, 8000, 6432, 6000, 628, 10424, 11207, 752, 93, 16800, 2916, 12919, 179, 292, 4104]}
[00:00:55] |Worker| {
    "history": {
        "input_ids": {
            "natural_cat": "tensor([9, 25], dtype=torch.int64)"
        },
        "attention_mask": "tensor([9, 25], dtype=torch.int64)"
    },
    "bid": {
        "input_ids": {
            "natural_cat": "tensor([5, 25], dtype=torch.int64)"
        },
        "attention_mask": "tensor([5, 25], dtype=torch.int64)"
    },
    "click": "int",
    "uid": "int64",
    "__clicks_mask__": "tensor([9], dtype=torch.int64)"
}
  3%|█████                                                                                                                                                                   | 511/16833 [00:01<00:44, 363.21it/s]
Traceback (most recent call last):
  File "/scratch/yz6201/Legommenders/worker.py", line 489, in <module>
    worker.run()
  File "/scratch/yz6201/Legommenders/worker.py", line 447, in run
    self.test_llm_layer_split()
  File "/scratch/yz6201/Legommenders/worker.py", line 422, in test_llm_layer_split
    pager.run()
  File "/scratch/yz6201/Legommenders/loader/pager/base_pager.py", line 31, in run
    self._process()
  File "/scratch/yz6201/Legommenders/loader/pager/base_pager.py", line 48, in _process
    output = self.model(**features)
  File "/scratch/yz6201/Legommenders/model/operators/llama_operator.py", line 45, in get_all_hidden_states
    layer_outputs = decoder_layer(
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 305, in forward
    hidden_states = self.mlp(hidden_states)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 155, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ext3/miniconda3/envs/nlp_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 538.00 MiB. GPU 0 has a total capacity of 31.74 GiB of which 323.12 MiB is free. Including non-PyTorch memory, this process has 31.42 GiB memory in 
use. Of the allocated memory 30.91 GiB is allocated by PyTorch, and 147.89 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_
segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
if this allocation of resources doesn't succeed, would you recommend us to reduce the data size like doing data distillation, etc? Or do you suggest us to reduce the model complexity? If so, could you please share some instructions based on this? Thank you for your help!

**Comment by Jyonn** [comment]
Hi, it seems you did not correctly set the page size.

As you can see in your json configuration log: `"page_size": 512`.

Please add `--page_size 32` in the command and try again, thanks!

**Comment by nemesisXX** [comment]
I honestly tried page size from 32 to 512, and they are all OOM. It's just the OOM ratio is different. So I think this method might not work for my case. Thank you for your help.

**Comment by Jyonn** [comment]
Maybe you can try `--page_size 1` and `--batch_size 1`. It should work. Then increaze your page size and batch size.

**Comment by Jyonn** [comment]
Llama-7b might be too large for your 32G GPU, so a smaller page size could work.

**Comment by nemesisXX** [comment]
Yes, you are right. I tried—-page_size 4 and—-batch_size 32 as the origin of the training preparation, and it works! But it was still too large when I tried to run worker.py on the training and testing part. It will cause around 62 hours if it's not OOM. We will try to use other resources like A100 80g if we can gain them. Thank you. But the code proves to be robust and has no problems at all.

**Comment by Jyonn** [comment]
You are welcome. Another acceleration mechanism is to use low-precise float type (e.g., bit 8) to load the LLM model. Some configuration should be added in model loading (`model/operators/llama_operator.py`):

```
self.transformer = LlamaModel.from_pretrained(self.config.llm_dir)  # type: LlamaModel
```

Note that, batch size is not important during preparation and try to increase the page size as large as possible.
